version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: alxlen/kittygram_backend
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    image: alxlen/kittygram_frontend
    command: cp -r /app/build/. /static/
    depends_on:
      - backend
    volumes:
      - static:/static
  gateway:
    image: alxlen/kittygram_gateway
    ports:
      - 9000:80
    depends_on:
      - frontend
    volumes:
      - static:/static
      - media:/media
